---
- name: Install HAProxy
  package:
    name: haproxy
    state: present

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'

- name: Ensure HAProxy service is running
  service:
    name: haproxy
    state: started
    enabled: yes
